version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=atomtibi
      - POSTGRES_PASSWORD=thib
      - POSTGRES_DB=webproject
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=atomtibi
      - POSTGRES_PASSWORD=thib
      - POSTGRES_DB=webproject
      - POSTGRES_PORT=5432

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
