apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: your-registry/node-app:latest  # Remplacez par l'image correcte
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          value: atomtibi
        - name: POSTGRES_PASSWORD
          value: thib
        - name: POSTGRES_DB
          value: webproject
        - name: POSTGRES_HOST
          value: db
      imagePullSecrets:
      - name: regcred  # Si nécessaire pour accéder à votre registre d'images privé
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        env:
        - name: POSTGRES_USER
          value: atomtibi
        - name: POSTGRES_PASSWORD
          value: thib
        - name: POSTGRES_DB
          value: webproject
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000  # Optional: only needed if you want to expose the service on a specific port on each node
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
